version: "3.7"
services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
#      - ./go-wait:/usr/local/bin/go-wait
      - ./go-auth-plugin:/usr/local/bin/go-auth-plugin
#      - ./go-auth-plugin.socket:/usr/local/kong/go-auth-plugin.socket
#      - ./go-wait:/usr/local/kong/go-wait.socket
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=go-auth-plugin
      - KONG_PLUGINSERVER_NAMES=go-auth-plugin
#      - KONG_PLUGINSERVER_GO_WAIT_QUERY_CMD=/usr/local/bin/go-wait -dump
      - KONG_PLUGINSERVER_GO_AUTH_PLUGIN_QUERY_CMD=/usr/local/bin/go-auth-plugin -dump
#      - KONG_PLUGINSERVER_GO_WAIT_SOCKET=/usr/local/kong/go-wait.socket
#      - KONG_PLUGINSERVER_GO_AUTH_PLUGIN_SOCKET=/usr/local/kong/go-auth-plugin.socket
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8002:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"